# Generated by Django 5.1.6 on 2025-03-31 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('not_applied', 'Not Applied')], default='not_applied', max_length=20),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role_id',
        ),
        migrations.RenameField(
            model_name='jobseeker',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('recruiter', 'Recruiter'), ('admin', 'Admin')], default='job_seeker', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
