# Generated by Django 5.1.6 on 2025-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobapplication_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
