# Generated by Django 5.1.6 on 2025-04-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
    ]
